# Generated by Django 6.0.2 on 2026-02-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuroTech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='diameter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pore_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
